# Generated by Django 2.0.7 on 2018-07-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('user_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lose', models.IntegerField()),
            ],
        ),
    ]
